[package]
name = "f3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.12"
ratatui = "0.26"
crossterm = "0.27"

[profile.dev]
